routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('users', 'UserController');
Route::put('/users/{user_id}/company/{company_id}', 'UserController@attach')->name('users.attach');
Route::delete('/users/{user_id}/company/{company_id}', 'UserController@detach')->name('users.detach');

Route::resource('companies', 'CompanyController');
Route::put('/companies/{company_id}/user/{user_id}', 'CompanyController@attach')->name('companies.attach');
Route::delete('/companies/{company_id}/user/{user_id}', 'CompanyController@detach')->name('companies.detach');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Start page</div>

                <div class="card-body">
                    <a class="btn btn-primary" href="{{ route('companies.index') }}">List of Companies</a>
                    <a class="btn btn-primary" href="{{ route('users.index') }}">List of Users</a>
                    <a class="btn btn-primary" href="/docs" target="_blank">Documentation</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection