routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('users', 'UserController');
Route::put('/users/{user_id}/company/{company_id}', 'UserController@attach')->name('users.attach');
Route::delete('/users/{user_id}/company/{company_id}', 'UserController@detach')->name('users.detach');

Route::resource('companies', 'CompanyController');
Route::put('/companies/{company_id}/user/{user_id}', 'CompanyController@attach')->name('companies.attach');
Route::delete('/companies/{company_id}/user/{user_id}', 'CompanyController@detach')->name('companies.detach');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'company';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['company', 'user_id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at', 'updated_at',
    ];

    /**
     * The users that belong to the company.
     */
    public function users()
    {
        return $this->belongsToMany('App\User', 'user_company');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use App\UserCompany;

class CompanyController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Where to redirect users after registration.
     *
     * @var string
     */
    protected $redirectTo = '/companies';

    /**
     * Get the post create / update redirect path.
     *
     * @return string
     */
    public function redirectPath()
    {
        if (method_exists($this, 'redirectTo')) {
            return $this->redirectTo();
        }

        return property_exists($this, 'redirectTo') ? $this->redirectTo : '/companies';
    }

    /**
     * Display a listing of the companies.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::all();

        $trashed_companies = Company::onlyTrashed()->get();

        return view('company.index', [
            'companies' => $companies,
            'trashed_companies' => $trashed_companies
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $this->validator($data)->validate();

        $data['user_id'] = Auth::id();

        Company::create($data);

        return redirect($this->redirectPath());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = $this->getCompanyBy($id);

        $related_users_id = UserCompany::select('user_id')
            ->where('company_id', $company->id)
            ->get();

        $users = User::whereNotIn('id', $related_users_id)->get();

        return view('company.show', [
            'company' => $company,
            'users' => $users
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = $this->getCompanyBy($id);

        return view('company.edit', ['company' => $company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = $this->getCompanyBy($id);

        $data = $request->all();

        $this->validator($data)->validate();

        $company->company = $data['company'];
        $company->user_id = Auth::id();

        $company->save();

        return redirect($this->redirectPath());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = $this->getCompanyBy($id);

        $company->delete();

        return redirect($this->redirectPath());
    }

    /**
     * Attaching a new user.
     *
     * @param  int  $user_id
     * @param  int  $company_id
     * @return \Illuminate\Http\Response
     */
    public function attach($company_id, $user_id)
    {
        $company = $this->getCompanyBy($company_id);

        $user = $this->getUserBy($user_id);

        if (!UserCompany::where(['user_id' => $user->id, 'company_id' => $company->id])->exists()) {
            $company->users()->attach($user->id);
        }

        return redirect(route('companies.show', ['id' => $company->id]));
    }

    /**
     * Detaching relation.
     *
     * @param  int  $user_id
     * @param  int  $company_id
     * @return \Illuminate\Http\Response
     */
    public function detach($user_id, $company_id)
    {
        $company = $this->getCompanyBy($company_id);

        $user = $this->getUserBy($user_id);

        if (UserCompany::where(['user_id' => $user->id, 'company_id' => $company->id])->exists()) {
            $company->users()->detach($user->id);
        }

        return redirect(route('companies.show', ['id' => $company->id]));
    }

    /**
     * Getting a user by ID.
     *
     * @param  int  $id
     * @return \App\Company
     */
    protected function getUserBy($id)
    {
        return User::findOrFail($id);
    }

    /**
     * Getting a company by ID.
     *
     * @param  int  $id
     * @return \App\Company
     */
    protected function getCompanyBy($id)
    {
        return Company::findOrFail($id);
    }

    /**
     * Get a validator for an incoming store / update request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'company' => 'required|max:255|unique:company',
        ]);
    }
}

resources/views/company/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create Company') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('companies.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Company') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('company') ? ' is-invalid' : '' }}" name="company" value="{{ old('company') }}" required autofocus>

                                @if ($errors->has('company'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('company') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Create') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit Company') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('companies.update', ['id' => $company->id]) }}" style="width: 100%">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Company') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('company') ? ' is-invalid' : '' }}" name="company" value="{{ $company->company }}" required autofocus>

                                @if ($errors->has('company'))
                                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $errors->first('company') }}</strong>
                            </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Edit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/company/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">List of companies</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="col-lg-12">

                        <a class="btn btn-primary" href="{{ route('companies.create') }}">Create</a>

                    </div><hr>
                    @if ($companies->count() > 0)
                        @foreach ($companies as $company)
                            <div class="col-lg-12">
                                <div class="row">
                                    <div class="col-lg-12"><p>This is company {{ $company->company }}.</p></div>
                                    <div class="col-lg-4">
                                        <a class="btn btn-primary" href="/companies/{{ $company->id }}/edit">Edit</a>
                                        <a class="btn btn-primary" href="/companies/{{ $company->id }}">Show</a>
                                    </div>
                                    <div class="offset-lg-6 col-lg-2">
                                        <form method="POST" action="/companies/{{ $company->id }}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-primary">Delete</button>
                                        </form>
                                    </div>
                                </div>
                            </div><hr>
                        @endforeach
                    @else
                        <div class="alert alert-error" role="alert">
                            Create a new company.
                        </div>
                    @endif

                </div>
            </div>
            <br>
            @if($trashed_companies->count() > 0)
                <div class="card">
                    <div class="card-header">List of deleted companies</div>

                    <div class="card-body">
                        @if ($trashed_companies->count() > 0)
                            @foreach ($trashed_companies as $company)
                                <div class="col-lg-12">
                                    <div class="row">
                                        <div class="col-lg-12"><span>This is company {{ $company->company }}.</span></div>
                                    </div>
                                </div><hr>
                            @endforeach
                        @else
                            <div class="alert alert-error" role="alert">
                                Create a new company.
                            </div>
                        @endif

                    </div>
                </div>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/company/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row">
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-body">
                            <table class="table">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Company</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <th scope="row">{{ $company->id }}</th>
                                    <td>{{ $company->company }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">

                        <div class="card">
                            <div class="card-header">{{ __('Available Users') }} <span class="badge badge-pill badge-success">Click to attach</span></div>

                            <div class="card-body">
                                @if ($users->count() > 0)
                                    @foreach ($users as $user)
                                        <form method="POST" action="{{ route('companies.attach', ['company_id' => $company->id, 'user_id' => $user->id]) }}" style="display: inline-block; margin-bottom: 5px;">
                                            @csrf
                                            @method('PUT')
                                            <button class="btn btn-outline-success">{{ $user->email }}</button>
                                        </form>
                                    @endforeach
                                @else
                                    <p>No available users</p>
                                @endif
                            </div>
                        </div>

                </div>
                <div class="col-lg-4">

                        <div class="card">
                            <div class="card-header">{{ __('Related Users') }} <span class="badge badge-pill badge-danger">Click to detach</span></div>

                            <div class="card-body">
                                @if ($company->users()->count() > 0)
                                    @foreach ($company->users as $user)
                                        <form method="POST" action="{{ route('companies.detach', ['company_id' => $company->id, 'user_id' => $user->id]) }}" style="display: inline-block; margin-bottom: 5px;">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-outline-danger">{{ $user->email }}</button>
                                        </form>
                                    @endforeach
                                @else
                                    <p>No related users</p>
                                @endif
                            </div>
                        </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection