routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('users', 'UserController');
Route::put('/users/{user_id}/company/{company_id}', 'UserController@attach')->name('users.attach');
Route::delete('/users/{user_id}/company/{company_id}', 'UserController@detach')->name('users.detach');

Route::resource('companies', 'CompanyController');
Route::put('/companies/{company_id}/user/{user_id}', 'CompanyController@attach')->name('companies.attach');
Route::delete('/companies/{company_id}/user/{user_id}', 'CompanyController@detach')->name('companies.detach');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The companies that belong to the user.
     */
    public function companies()
    {
        return $this->belongsToMany('App\Company', 'user_company', 'user_id', 'company_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Company;
use Illuminate\Http\Request;
use App\UserCompany;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Where to redirect users after registration.
     *
     * @var string
     */
    protected $redirectTo = '/users';

    /**
     * Get the post create / update redirect path.
     *
     * @return string
     */
    public function redirectPath()
    {
        if (method_exists($this, 'redirectTo')) {
            return $this->redirectTo();
        }

        return property_exists($this, 'redirectTo') ? $this->redirectTo : '/users';
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:6', 'confirmed'],
        ]);
    }

    /**
     * Display a listing of the users.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        $trashed_users = User::onlyTrashed()->get();

        return view('user.index', [
            'users' => $users,
            'trashed_users' => $trashed_users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validator($request->all())->validate();

        $data = $request->all();

        User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
        ]);

        return redirect($this->redirectPath());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = $this->getUserBy($id);

        $related_companies_id = UserCompany::select('company_id')
            ->where('user_id', $user->id)
            ->get();

        $companies = Company::whereNotIn('id', $related_companies_id)->get();

        return view('user.show', [
            'user' => $user,
            'companies' => $companies
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->getUserBy($id);

        return view('user.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = $this->getUserBy($id);

        $this->validator($request->all())->validate();

        $data = $request->all();

        $user->update([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
        ]);

        return redirect($this->redirectPath());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = $this->getUserBy($id);

        if ($user->id == Auth::id()) {
            abort(403);
        }

        $user->delete();

        return redirect($this->redirectPath());
    }

    /**
     * Attaching a new company.
     *
     * @param  int  $user_id
     * @param  int  $company_id
     * @return \Illuminate\Http\Response
     */
    public function attach($user_id, $company_id)
    {
        $user = $this->getUserBy($user_id);

        $company = $this->getCompanyBy($company_id);

        if (!UserCompany::where(['user_id' => $user->id, 'company_id' => $company->id])->exists()) {
            $user->companies()->attach($company->id);
        }

        return redirect(route('users.show', ['id' => $user->id]));
    }

    /**
     * Detaching relation.
     *
     * @param  int  $user_id
     * @param  int  $company_id
     * @return \Illuminate\Http\Response
     */
    public function detach($user_id, $company_id)
    {
        $user = $this->getUserBy($user_id);

        $company = $this->getCompanyBy($company_id);

        if (UserCompany::where(['user_id' => $user->id, 'company_id' => $company->id])->exists()) {
            $user->companies()->detach($company->id);
        }

        return redirect(route('users.show', ['id' => $user->id]));
    }

    /**
     * Getting a company by ID.
     *
     * @param  int  $id
     * @return \App\Company
     */
    protected function getCompanyBy($id)
    {
        return Company::findOrFail($id);
    }

    /**
     * Getting a user by ID.
     *
     * @param  int  $id
     * @return \App\Company
     */
    protected function getUserBy($id)
    {
        return User::findOrFail($id);
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create User') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('users.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Create') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="card">
                    <div class="card-header">{{ __('Edit User') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('users.update', ['id' => $user->id]) }}" style="width: 100%">
                            @csrf
                            @method('PUT')
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ $user->name }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ $user->email }}" required>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                    @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('password') }}</strong>
                                </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Edit') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">List of users.</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="col-lg-12">

                        <a class="btn btn-primary" href="{{ route('users.create') }}">Create</a>

                    </div><hr>
                    @if ($users->count() > 0)
                        @foreach ($users as $user)
                            <div class="col-lg-12">
                                <div class="row">
                                    <div class="col-lg-12"><p>This is {{ $user->name }}.</p></div>
                                    <div class="col-lg-4">
                                        <a class="btn btn-primary" href="/users/{{ $user->id }}/edit">Edit</a>
                                        <a class="btn btn-primary" href="/users/{{ $user->id }}">Show</a>
                                    </div>
                                    <div class="offset-lg-6 col-lg-2">
                                        <form method="POST" action="/users/{{ $user->id }}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-primary">Delete</button>
                                        </form>
                                    </div>
                                </div>
                            </div><hr>
                        @endforeach
                    @else
                        <div class="alert alert-error" role="alert">
                            Create a new user.
                        </div>
                    @endif
                </div>
            </div>
            <br>
            @if ($trashed_users->count() > 0)
            <div class="card">
                <div class="card-header">List of deleted users.</div>

                <div class="card-body">
                    @foreach ($trashed_users as $user)
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-12"><span>This is {{ $user->name }}.</span></div>
                            </div>
                        </div><hr>
                    @endforeach
                </div>
            </div>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row">
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-header">{{ __('User info') }}</div>
                        <div class="card-body">
                            <div class="row">
                                <table class="table">
                                    <thead class="thead-light">
                                    <tr>
                                        <th scope="col">ID</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Email</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <th scope="row">{{ $user->id }}</th>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-header">{{ __('Available Companies') }} <span class="badge badge-pill badge-success">Click to attach</span></div>

                        <div class="card-body">
                            @if ($companies->count())
                                @foreach ($companies as $company)
                                    <form method="POST" action="{{ route('users.attach', ['user_id' => $user->id, 'company_id' => $company->id]) }}" style="display: inline-block; margin-bottom: 5px;">
                                        @csrf
                                        @method('PUT')
                                        <button class="btn btn-outline-success">{{ $company->company }}</button>
                                    </form>
                                @endforeach
                            @else
                                <p>No available companies</p>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-header">{{ __('Related Companies') }} <span class="badge badge-pill badge-danger">Click to detach</span></div>

                        <div class="card-body">
                            @if ($user->companies->count())
                                @foreach ($user->companies as $company)
                                    <form method="POST" action="{{ route('users.detach', ['user_id' => $user->id, 'company_id' => $company->id]) }}" style="display: inline-block; margin-bottom: 5px;">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-outline-danger">{{ $company->company }}</button>
                                    </form>
                                @endforeach
                            @else
                                <p>No related companies</p>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection